CREATE TABLE IF NOT EXISTS jobs (
  id TEXT PRIMARY KEY,
  user TEXT,
  spec TEXT,
  status TEXT,
  result TEXT,
  ts_created DATETIME DEFAULT CURRENT_TIMESTAMP,
  ts_updated DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  ts_created DATETIME DEFAULT CURRENT_TIMESTAMP
);
